
###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "nombreUsuario" : "ana",
    "nombre" : "bena",
    "password" : "123",
    "correo" : "bii3eeaa@example.com",
    "telefono" : "12345678",
    "idRol" : 2 ,
    "ci" : "2134547"
}
###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "nombreUsuario": "ana",	
    "password": "ana123"
}

